<a href="https://colab.research.google.com/github/stephenbeckr/numerical-analysis-class/blob/master/Demos/Misc_speedExamples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Speed considerations in Python
In Matlab, most students know the cardinal rule of "avoid `for` loops. In Python, this is still true, but there are more alternatives, and if you use the wrong alternative, the code may still be slow. The basic Python constructions are good for maintaining and debugging code, but not necessarily for speed. The rule-of-thumb is that if there is a `numpy` version that does the same thing as the basic Python version, then the `numpy` version is faster.

## An example (from HW 4): finding the maximum of an array

In [16]:
import numpy as np
from numpy.linalg import norm
from timeit import timeit


n = int(1e7)
x = np.random.randn(n)
xList = x.tolist()

In [17]:
%time max(abs(x))

CPU times: user 969 ms, sys: 4.84 ms, total: 973 ms
Wall time: 976 ms


5.583159866604084

In [18]:
%time max(abs(xx) for xx in xList)

CPU times: user 806 ms, sys: 1.9 ms, total: 807 ms
Wall time: 809 ms


5.583159866604084

In [19]:
%time np.max(np.abs(x))

CPU times: user 24.2 ms, sys: 2.01 ms, total: 26.2 ms
Wall time: 29 ms


5.583159866604084

In [20]:
%time norm(x,ord=np.inf)

CPU times: user 25.7 ms, sys: 0 ns, total: 25.7 ms
Wall time: 30.1 ms


5.583159866604084

## Another example of timing (from HW 4 too)

In [5]:
f = lambda x : np.sin(20*x)
n=1e7;
x = np.linspace(1,2,int(n))

@np.vectorize # This tells Python to apply np.vectorize to the following function
def g_slow(x):
  if x < 1.3:
    return f(x)
  else:
    return f(2.6-x)
g1 = lambda x : (x<1.3)*f(x) + (x>=1.3)*f(2.6-x)
g2 = lambda x : np.piecewise( x, x<1.3, [f, lambda x : f(2.6-x)] )

In [6]:
%time g_slow(x)

CPU times: user 11.8 s, sys: 537 ms, total: 12.3 s
Wall time: 12.4 s


array([ 0.91294525,  0.91294607,  0.91294688, ..., -0.53656954,
       -0.53657123, -0.53657292])

In [7]:
%time g1(x)

CPU times: user 501 ms, sys: 51 ms, total: 552 ms
Wall time: 557 ms


array([ 0.91294525,  0.91294607,  0.91294688, ..., -0.53656954,
       -0.53657123, -0.53657292])

In [8]:
%time g2(x)

CPU times: user 3.75 s, sys: 36.1 ms, total: 3.79 s
Wall time: 3.79 s


array([ 0.91294525,  0.91294607,  0.91294688, ..., -0.53656954,
       -0.53657123, -0.53657292])